# Generated by Django 3.2.3 on 2021-06-06 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vehiculo_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('nombreOb', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nombre de la Obra')),
                ('autor', models.CharField(max_length=30, verbose_name='Autor')),
                ('año', models.CharField(max_length=10, verbose_name='Año')),
                ('tecnica', models.CharField(max_length=50, verbose_name='Técnica')),
                ('tamaño', models.CharField(max_length=10, verbose_name='Tamaño')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, verbose_name='Email')),
                ('contraseña', models.CharField(max_length=30, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=200, verbose_name='mensaje')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
