# Generated by Django 3.2.3 on 2021-06-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contacto_obra_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='tamaño',
            field=models.CharField(max_length=20, verbose_name='Tamaño'),
        ),
    ]
