# Generated by Django 3.2.3 on 2021-06-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_obra_año'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='nombreOb',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre de la Obra'),
        ),
    ]
