# Generated by Django 3.2.3 on 2021-06-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_obra_nombreob'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
