# Generated by Django 3.2.3 on 2021-06-30 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usuario_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='imagen',
        ),
    ]
