# Generated by Django 3.2.3 on 2021-07-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_usuario_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagen',
        ),
    ]
